### ISSUE TITLE
Augmenter le nombre de lignes max retournées et le timeout sql

### ISSUE THREAD

**Issue by ColinMaudry** [ColinMaudry/decp-table-schema-utils#31]

**Comment by ColinMaudry** [comment]
Le nombre max de lignes est fixé à 50 000 lignes. Un message s'affiche si l'ensemble des lignes ne pourront être exportées.

cc @johanricher

**Comment by ColinMaudry** [comment]
Il faut à peu près 35 secondes sur le serveur pour produire un XLSX de 50 000 lignes. 26 secondes en local.

**Comment by johanricher** [comment]
Merci Colin, je viens de tester et ça marche effectivement ! Le seul problème du point de vue utilisateur c'est en effet l'attente lors de la création du fichier et l'absence de feedback dans l'UI qui peut laisser penser que ça a planté. Certains utilisateurs pourraient être amenés à cliquer à nouveau ou à raffraichir la page. Mais c'est secondaire puisque ça marche donc l'objectif est atteint. :+1:
