### ISSUE TITLE
Utiliser le ; comme séparateur du CSV

### ISSUE THREAD

**Issue by ColinMaudry** [ColinMaudry/decp-table-schema-utils#6]

**Comment by johanricher** [comment]
Table Schema n’a aucune notion de séparateur, il travaille au niveau au-dessus, sur les données tabulaires et pas leur sérialisation CSV. Par conséqunt, cette spécification n’a pas lieu d’être et ne se retrouve pas dans les schémas SCDL écrits au format Table Schema. C'est pour cela que Validata peut valider tout type de fichiers tabulaires (.csv, .tsv, mais aussi xlsx, .xls, .ods, etc. ).

**Comment by ColinMaudry** [comment]
@johanricher Effectivement je n'y voyais aucune référence. Merci c'est plus clair !
